name: X-Prison
version: 1.12.9
main: dev.drawethree.xprison.XPrison
depend: [ Vault, WorldGuard, WorldEdit, helper ]
softdepend:
  - PlaceholderAPI
  - JetsPrisonMines
  - MVdWPlaceholderAPI
  - Multiverse-Core
  - UltraBackpacks
authors: [ Drawethree ]
api-version: 1.13
load: POSTWORLD
website: www.drawethree.dev
