name: X-Prison
version: ${project.version}
main: dev.drawethree.xprison.XPrison
depend: [ Vault, WorldGuard, WorldEdit, helper ]
softdepend:
  - PlaceholderAPI
  - JetsPrisonMines
  - MVdWPlaceholderAPI
  - Multiverse-Core
  - UltraBackpacks
authors: [ Tomut0, Drawethree ]
api-version: 1.13
load: POSTWORLD
website: https://github.com/Tomut0
